"""Install or compare repository-owned files without replacing host configuration."""

import argparse
from datetime import datetime, timezone
import os
from pathlib import Path
import shutil
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
SKILLS = ("concept-exploration", "product-check", "dev-principles", "platform-port")


def installation_plan(root, home, target, *, rules=False, hook=False, codex_home=None):
    host = (codex_home or home / ".codex") if target == "codex" else home / ".claude"
    skills_root = home / ".agents" / "skills" if target == "codex" else host / "skills"
    files = {}
    for name in SKILLS:
        source = root / "skills" / name
        if not (source / "SKILL.md").is_file():
            raise ValueError(f"Missing SKILL.md: {name}")
        for path in sorted(source.rglob("*")):
            if path.is_symlink():
                raise ValueError(f"Source symlink requires manual review: {path}")
            if path.is_file() and "__pycache__" not in path.parts:
                files[skills_root / name / path.relative_to(source)] = path.read_bytes()
    if rules:
        common = (root / "AGENTS.md").read_text(encoding="utf-8-sig")
        adapter = (root / "adapters" / target / "instructions.md").read_text(encoding="utf-8")
        content = "<!-- Generated by agent-skills; edit the source repository. -->\n\n" + common + "\n\n" + adapter
        filename = "AGENTS.md" if target == "codex" else "CLAUDE.md"
        files[host / filename] = content.encode("utf-8")
    if hook:
        files[host / "hooks" / "methodology_guard.py"] = (root / "hooks" / "methodology_guard.py").read_bytes()
    return files, skills_root


def differences(files, skills_root):
    result = []
    for path, expected in files.items():
        if not path.is_file():
            result.append(("missing", path))
        elif path.read_bytes() != expected:
            result.append(("changed", path))
    for name in SKILLS:
        for path in (skills_root / name).rglob("*"):
            if path.is_file() and "__pycache__" not in path.parts and path not in files:
                result.append(("extra", path))
    return result


def install(files, skills_root, home, *, replace=False):
    drift = differences(files, skills_root)
    if any(kind == "extra" for kind, _ in drift):
        raise ValueError("Extra files exist in managed skills; review them manually. Nothing was written.")
    if not replace and any(kind == "changed" for kind, _ in drift):
        raise ValueError("Existing files differ. Review first; --replace explicitly permits backed-up replacement. Nothing was written.")
    for _, path in drift:
        for part in (path, *path.parents):
            if part.is_symlink() or (hasattr(part, "is_junction") and part.is_junction()):
                raise ValueError(f"Linked destination requires manual review: {part}")
        if path.exists() and not path.is_file():
            raise ValueError(f"Destination is not a file: {path}")

    backup = None
    changed = [path for kind, path in drift if kind == "changed"]
    if changed:
        base = home / ".agent-skills-backups"
        base.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ-")
        backup = Path(tempfile.mkdtemp(prefix=stamp, dir=base))
        for index, path in enumerate(changed):
            shutil.copy2(path, backup / f"{index}-{path.name}")
        (backup / "paths.txt").write_text("\n".join(str(path) for path in changed), encoding="utf-8")

    for _, path in drift:
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = None
        try:
            with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as stream:
                temp = Path(stream.name)
                stream.write(files[path])
            os.replace(temp, path)
        finally:
            if temp is not None and temp.exists():
                temp.unlink()
    return len(drift), backup


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("check", "install"))
    parser.add_argument("--target", required=True, choices=("codex", "claude-code"))
    parser.add_argument("--home", type=Path, help="Alternate user home, e.g. an isolated test directory")
    parser.add_argument("--codex-home", type=Path)
    parser.add_argument("--rules", action="store_true", help="Include generated global instructions")
    parser.add_argument("--hook-script", action="store_true", help="Include script only, never hook configuration or trust")
    parser.add_argument("--replace", action="store_true", help="Back up and replace conflicting managed files")
    args = parser.parse_args()
    home = (args.home or Path.home()).expanduser().resolve()
    codex_home = args.codex_home
    if codex_home is None and args.home is None and os.environ.get("CODEX_HOME"):
        codex_home = Path(os.environ["CODEX_HOME"])
    if codex_home is not None:
        codex_home = codex_home.expanduser().absolute()
    try:
        files, skills_root = installation_plan(ROOT, home, args.target, rules=args.rules, hook=args.hook_script, codex_home=codex_home)
        if args.action == "check":
            drift = differences(files, skills_root)
            for kind, path in drift:
                print(f"{kind}: {path}")
            if not drift:
                print(f"PASS: {len(files)} managed files match ({args.target}).")
            return int(bool(drift))
        count, backup = install(files, skills_root, home, replace=args.replace)
        print(f"Installed {count} files ({args.target}).")
        if backup:
            print(f"Backup: {backup}")
        print("Hook configuration and trust were not modified.")
        return 0
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
